---
widget: { class: widget }
sizer: { type: vertical }
children:
- widget:
    class: list
    id: assetType
    type: horizontal
    options:
    - id: animation
      text: Sprites
    - id: audioClip
      text: AudioClips
    - id: shader
      text: Shaders
- widget: { class: widget }
  proportion: 1
  border: [0, 10, 0, 0]
  children:
  - widget: { class: scrollBarPane }
    children:
    - widget: 
        class: list
        id: assetList
        size: [250, 20]
        options:
        - id: test0
          text: test
        - id: test1
          text: test
        - id: test2
          text: test
  - sizer: { type: vertical }
    proportion: 1
    children:
    - widget: { class: widget, id: contents }
      fill: fill
      sizer: { type: horizontal }
      proportion: 1
    - widget: { class: label, id: assetName, text: "" }
      fill: centre
...