---
widget: { class: image, image: "halley_ui/ui_window.png", innerBorder: [ 4, 4, 4, 4 ], colour: "#201427" }
sizer: { type: vertical }
children:
- widget: { id: scrollBarPane, class: scrollBarPane }
  sizer: { type: vertical, gap: 8 }
  proportion: 1
  border: [0, 0, 4, 0]
  children:
  - widget: { id: entityHeader, class: image, image: "ui/title_capsule.png", innerBorder: [ 4, 1, 4, 4 ], colour: "#754589" }
    sizer: { type: vertical }
    border: [0, 0, 0, 4]
    children:
    - widget: { id: "", class: label, text: "Entity" }
      fill: centre
    - widget: { id: entityFields, class: widget }
      border: [1, 4, 1, 1]
      sizer: { type: grid, gap: 2, columns: 2, columnProportion: [0, 1] }
      fill: fill
      children:
      - widget: { class: widget, size: [100, 20] }
        children:
        - widget: { id: "", class: label, text: "Name", style: "labelLight" }
      - widget: { id: entityName, class: textInput, size: [200, 22], style: inputThin }
        proportion: 1
  - widget: { id: prefabHeader, class: image, image: "ui/title_capsule.png", innerBorder: [ 4, 1, 4, 4 ], colour: "#754589" }
    sizer: { type: vertical }
    border: [0, 0, 0, 4]
    children:
    - widget: { id: "", class: label, text: "Prefab" }
      fill: centre
    - widget: { id: prefabFields, class: widget }
      border: [1, 4, 1, 1]
      sizer: { type: grid, gap: 2, columns: 2, columnProportion: [0, 1] }
      fill: fill
      children:
      - widget: { class: widget, size: [100, 20] }
        children:
        - widget: { id: "", class: label, text: "Prefab", style: "labelLight" }
      - widget: { id: prefabName, class: dropdown, size: [200, 30] }
        proportion: 1
  - widget: { id: fields, class: widget }
    sizer: { type: vertical, gap: 8 }
  - widget: { id: addComponentButton, class: button, text: "Add Component", size: [ 30, 25 ] }
...